#cloud-config
%{ if import_key != "" }
ssh_import_id:
- "${import_key}"
%{ endif }

write_files:

- path: /etc/ptfe/role
  owner: root:root
  permissions: "0444"
  content: "${role}"

- path: /etc/ptfe/ptfe_url
  owner: root:root
  permissions: "0644"
  content: "${installer_url}"

- path: /etc/ptfe/bootstrap-token
  owner: root:root
  permissions: "0400"
  content: "${bootstrap_token}"
%{ if role != "secondary" }

- path: /etc/ptfe/setup-token
  owner: root:root
  permissions: "0400"
  content: "${setup_token}"

- path: /etc/ptfe/primary-pki-url
  owner: root:root
  permissions: "0400"
  content: "${primary_pki_url}"
%{ endif }

- path: /etc/ptfe/cluster-api-endpoint
  owner: root:root
  permissions: "0400"
  content: "${cluster_api_endpoint}"

- path: /etc/ptfe/health-url
  owner: root:root
  permissions: "0400"
  content: "${health_url}"

- path: /etc/ptfe/assistant-host
  owner: root:root
  permissions: "0400"
  content: "${assistant_host}"

- path: /etc/ptfe/assistant-token
  owner: root:root
  permissions: "0400"
  content: "${assistant_token}"

- path: /etc/ptfe/role-id
  owner: root:root
  permissions: "0444"
  content: "${role_id}"

%{ if startup_script != "" }
- path: /var/lib/cloud/scripts/per-once/000-user-startup-script.sh
  owner: root:root
  permissions: "0555"
  encoding: gz+b64
  content: ${startup_script}
%{ endif }

- path: /var/lib/cloud/scripts/per-once/install-ptfe.sh
  owner: root:root
  permissions: "0555"
  encoding: gz+b64
  content: ${install_ptfe_sh}

- path: /etc/ptfe/proxy-url
  owner: root:root
  permissions: "0400"
  content: "${proxy_url}"

- path: /etc/ptfe/additional-no-proxy
  owner: root:root
  permissions: "0400"
  content: "${additional_no_proxy}"

- path: /etc/ptfe/custom-ca-cert-url
  owner: root:root
  permissions: "0400"
  content: "${ca_bundle_url}"

- path: /etc/profile.d/proxy.sh
  owner: root:root
  permissions: "0755"
  content: |
    export http_proxy="${proxy_url}"
    export https_proxy="${proxy_url}"
    export no_proxy=10.0.0.0/8,127.0.0.1,169.254.169.254,${cluster_api_lb}
%{ if additional_no_proxy != "" }
    export no_proxy=$no_proxy,${additional_no_proxy}
%{ endif }
%{ if repl_cidr != "" }
    export no_proxy=$no_proxy,${repl_cidr}
%{ endif }


%{ if airgap_installer_url != "" }
- path: /etc/ptfe/airgap-installer-url
  owner: root:root
  permissions: "0644"
  content: ${airgap_installer_url}
%{ endif }

%{ if role == "main" }
- path: /etc/replicated.rli
  owner: root:root
  permissions: "0444"
  encoding: b64
  content: ${license_b64}

- path: /etc/replicated-ptfe.conf
  owner: root:root
  permissions: "0644"
  encoding: gz+b64
  content: ${rptfeconf}

## https://help.replicated.com/docs/kb/developer-resources/automate-install/
- path: /etc/replicated.conf
  owner: root:root
  permissions: "0644"
  encoding: gz+b64
  content: ${replconf}

%{ if airgap_package_url != "" }
- path: /etc/ptfe/airgap-package-url
  owner: root:root
  permissions: "0644"
  content: ${airgap_package_url}
%{ endif }

%{ if weave_cidr != "" }
- path: /etc/ptfe/weave-cidr
  owner: root:root
  permissions: "0644"
  content: ${weave_cidr}
%{ endif }

%{ if repl_cidr != "" }
- path: /etc/ptfe/repl-cidr
  owner: root:root
  permissions: "0644"
  content: ${repl_cidr}
%{ endif }
%{ endif }

%{ if distro == "ubuntu" }
- path: /etc/apt/apt.conf.d/00_aaa_proxy.conf
  owner: root:root
  permissions: "0400"
  content: |
    Acquire::http::proxy "${proxy_url}";
    Acquire::https::proxy "${proxy_url}";

packages:
- jq
- chrony
- ipvsadm
- unzip
- wget
%{ endif }
